/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package producerconsumer;

/**
 *
 * @author FernandaLopez
 */

import javax.swing.*;

public class GUI extends javax.swing.JFrame {
    
    private DefaultListModel<String> toDo, done;
    private int totalDone, totalTodo;

    /**
     * Creates new form GUI
     */
    public GUI() {
        
        initComponents();
        this.toDo = new DefaultListModel<>();
        this.done = new DefaultListModel<>();
        this.totalDone = 0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tFtimeConsumers = new javax.swing.JTextField();
        tFbufferSize = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tFtimeProducers = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scrollToDo = new javax.swing.JScrollPane();
        todoList = new javax.swing.JList<>();
        scrollDone = new javax.swing.JScrollPane();
        doneList = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jSProducers = new javax.swing.JSpinner();
        jSConsumers = new javax.swing.JSpinner();
        jSMin = new javax.swing.JSpinner();
        jSMax = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jTtotalDone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTtotalTodo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Producers");

        jLabel2.setText("Consumers");

        jLabel3.setText("Qty");

        jLabel4.setText("Wait time\nin milliseconds");

        tFtimeConsumers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFtimeConsumersActionPerformed(evt);
            }
        });

        tFbufferSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFbufferSizeActionPerformed(evt);
            }
        });

        jLabel5.setText("Buffer Size");

        tFtimeProducers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFtimeProducersActionPerformed(evt);
            }
        });
        tFtimeProducers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tFtimeProducersKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tFtimeProducersKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFtimeProducersKeyReleased(evt);
            }
        });

        jLabel6.setText("Define range of numbers (min,max)\n");

        jLabel7.setText("From");

        jLabel8.setText("To");

        scrollToDo.setViewportView(todoList);

        scrollToDo.setViewportView(todoList);

        scrollDone.setViewportView(doneList);

        scrollDone.setViewportView(doneList);

        jLabel9.setText("TO DO");

        jLabel10.setText("DONE");

        btnStart.setText("START");

        jLabel11.setText("Total done operations\n");

        jTtotalDone.setEditable(false);
        jTtotalDone.setText("0");
        jTtotalDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtotalDoneActionPerformed(evt);
            }
        });

        jLabel12.setText("Total to do operations");

        jTtotalTodo.setEditable(false);
        jTtotalTodo.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jSMin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel8)
                                .addGap(49, 49, 49)
                                .addComponent(jSMax, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSProducers, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                            .addComponent(jSConsumers))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tFtimeConsumers, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tFtimeProducers, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(97, 97, 97)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tFbufferSize, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(96, 96, 96))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTtotalTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnStart)
                                        .addGap(51, 51, 51)
                                        .addComponent(scrollDone, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTtotalDone, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tFtimeProducers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSProducers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tFbufferSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tFtimeConsumers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSConsumers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jSMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrollToDo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(scrollDone, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnStart)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTtotalDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTtotalTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tFtimeConsumersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFtimeConsumersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFtimeConsumersActionPerformed

    private void tFbufferSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFbufferSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFbufferSizeActionPerformed

    private void tFtimeProducersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFtimeProducersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFtimeProducersActionPerformed

    private void jTtotalDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtotalDoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtotalDoneActionPerformed

    private void tFtimeProducersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFtimeProducersKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tFtimeProducersKeyTyped

    private void tFtimeProducersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFtimeProducersKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tFtimeProducersKeyReleased

    private void tFtimeProducersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFtimeProducersKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tFtimeProducersKeyPressed

    private void tfTimeProducersKeyTyped(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:

    } 
    
    private void tfTimeConsumersKeyTyped(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    } 
    
    private void tfBufferSizeKeyTyped(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    } 
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.startProgram = true;
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    public JButton getStartButton(){
        return this.btnStart;
    }
    
    private void addTask(DefaultListModel listModel, JList list, JScrollPane scrollPane){
        list.setModel(listModel);
        scrollPane.setViewportView(list);
    }
    
    public void removeTodo(){
        if(this.toDo.size()>0){
            this.toDo.remove(0);
            this.addTask(this.toDo, this.todoList, this.scrollToDo);
        }
    }
    
    public void addTodo(String task){
        System.out.println(task);
        this.toDo.addElement(task);
        this.addTask(this.toDo, this.todoList, this.scrollToDo);
    }
    
    public void addDone(String task){
        System.out.println(task);
        this.done.addElement(task);
        this.addTask(this.done, this.doneList, this.scrollDone);
    }
    
    public void increaseTotalDone(){
        this.totalDone++;
        this.totalTodo--;
        this.jTtotalDone.setText(this.totalDone + "");
        this.jTtotalTodo.setText(this.totalTodo + "");
    }
    
    public void increaseTotalTodo(){
        this.totalTodo++;
        this.jTtotalTodo.setText(this.totalTodo + "");
    }
    
    public boolean startProgram = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JList<String> doneList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSConsumers;
    private javax.swing.JSpinner jSMax;
    private javax.swing.JSpinner jSMin;
    private javax.swing.JSpinner jSProducers;
    private javax.swing.JTextField jTtotalDone;
    private javax.swing.JTextField jTtotalTodo;
    private javax.swing.JScrollPane scrollDone;
    private javax.swing.JScrollPane scrollToDo;
    private javax.swing.JTextField tFbufferSize;
    private javax.swing.JTextField tFtimeConsumers;
    private javax.swing.JTextField tFtimeProducers;
    private javax.swing.JList<String> todoList;
    // End of variables declaration//GEN-END:variables

public int getMinRange(){
    return (int) this.jSMin.getValue(); 
}
public int getMaxRange(){
    return (int) this.jSMax.getValue();
    }
public int getConsumers(){
    return (int) this.jSConsumers.getValue();
    }
public int getProducers(){
    return (int) this.jSProducers.getValue();
    }
public long getConsumerTime(){
    try{
       return (long) Long.parseLong(this.tFtimeConsumers.getText());
    } catch(NumberFormatException ex){
        return -1;
    }
    
}
public long getProducerTime(){
    try{
       return (long) Long.parseLong(this.tFtimeProducers.getText());
    } catch(NumberFormatException ex){
        return -1;
    }
        
    }
public int getBufferSize(){
        try{
       return (int) Integer.parseInt(this.tFbufferSize.getText());
    } catch(NumberFormatException ex){
        return -1;
    }
        
    }
}


